spring:
  output:
    ansi:
      enabled: ALWAYS   # 🌈 Habilita cores no console

# ============================================================
# 🔧 Configurações do Aplicativo
# ============================================================
app:
  kafka:
    topic: pagamentos-topic

# ============================================================
# 🪵 Logging
# ============================================================
logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
